# Generated by Django 3.2.8 on 2021-10-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmesFavorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_filme', models.CharField(max_length=50)),
                ('ator_principal', models.CharField(max_length=50)),
                ('sinopse_do_filme', models.TextField()),
                ('classificação', models.CharField(choices=[('F', 'Apenas maiores de 18 anos'), ('M', 'Apenas maiores de 16 anos'), ('N', 'Livre para todas idades')], max_length=100, verbose_name='classificação')),
                ('assistido_no_cinema', models.BooleanField(blank=True, null=True)),
                ('data_de_lançamento', models.DateField()),
            ],
        ),
    ]
