# Generated by Django 3.2.8 on 2021-10-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmesfavorito',
            name='classificação',
            field=models.CharField(choices=[('18', 'Apenas maiores de 18 anos'), ('16', 'Apenas maiores de 16 anos'), ('Livre', 'Livre para todas idades')], max_length=100, verbose_name='classificação'),
        ),
    ]
